version: '3.1'

services:

  db:
    #image: mysql
    build: ./db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  restful:
    build: ./restful
    ports:
      - 8090:8080
      
  ui:
    build: ./ui
    ports:
      - 8080:8080
      